/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MossaService } from "../mossa.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MossaCreateInput } from "./MossaCreateInput";
import { Mossa } from "./Mossa";
import { MossaFindManyArgs } from "./MossaFindManyArgs";
import { MossaWhereUniqueInput } from "./MossaWhereUniqueInput";
import { MossaUpdateInput } from "./MossaUpdateInput";
import { AddMossaDto } from "../AddMossaDto";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MossaControllerBase {
  constructor(
    protected readonly service: MossaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Mossa })
  @nestAccessControl.UseRoles({
    resource: "Mossa",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMossa(@common.Body() data: MossaCreateInput): Promise<Mossa> {
    return await this.service.createMossa({
      data: {
        ...data,

        mano: data.mano
          ? {
              connect: data.mano,
            }
          : undefined,

        giocatore: data.giocatore
          ? {
              connect: data.giocatore,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        azione: true,

        mano: {
          select: {
            id: true,
          },
        },

        giocatore: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Mossa] })
  @ApiNestedQuery(MossaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Mossa",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mossas(@common.Req() request: Request): Promise<Mossa[]> {
    const args = plainToClass(MossaFindManyArgs, request.query);
    return this.service.mossas({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        azione: true,

        mano: {
          select: {
            id: true,
          },
        },

        giocatore: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Mossa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mossa",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async mossa(
    @common.Param() params: MossaWhereUniqueInput
  ): Promise<Mossa | null> {
    const result = await this.service.mossa({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        azione: true,

        mano: {
          select: {
            id: true,
          },
        },

        giocatore: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Mossa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mossa",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMossa(
    @common.Param() params: MossaWhereUniqueInput,
    @common.Body() data: MossaUpdateInput
  ): Promise<Mossa | null> {
    try {
      return await this.service.updateMossa({
        where: params,
        data: {
          ...data,

          mano: data.mano
            ? {
                connect: data.mano,
              }
            : undefined,

          giocatore: data.giocatore
            ? {
                connect: data.giocatore,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          azione: true,

          mano: {
            select: {
              id: true,
            },
          },

          giocatore: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Mossa })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Mossa",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMossa(
    @common.Param() params: MossaWhereUniqueInput
  ): Promise<Mossa | null> {
    try {
      return await this.service.deleteMossa({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          azione: true,

          mano: {
            select: {
              id: true,
            },
          },

          giocatore: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/mossa")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async AddMossa(
    @common.Body()
    body: AddMossaDto
  ): Promise<string> {
    return this.service.AddMossa(body);
  }
}
